needs-integration-test:
  - changed-files:
      - any-glob-to-any-file:
          - 'pkg/snapshot-agent/**'
          - 'cmd/snapshot-agent/**'
          - 'pkg/client/python/timeslice/snapshot_agent/**'
          - 'tests/integration/**'
