# Default values for snapshot-agent.
image:
  repository: ghcr.io/llm-d/snapshot-agent
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources: {}
#  limits:
#    cpu: 500m
#    memory: 1Gi
#  requests:
#    cpu: 100m
#    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

port: 9001
