# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from timeslice.orchestrator._generated import accelerator_orchestrator_pb2 as timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in timeslice/orchestrator/_generated/accelerator_orchestrator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AcceleratorOrchestratorServiceStub:
    """AcceleratorOrchestratorService provides APIs for managing accelerator orchestration.
    It coordinates access to shared accelerators among multiple jobs in a time-slice group.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Acquire = channel.unary_unary(
                '/accelerator_orchestrator.v1alpha1.AcceleratorOrchestratorService/Acquire',
                request_serializer=timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.AcquireRequest.SerializeToString,
                response_deserializer=timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.AcquireResponse.FromString,
                _registered_method=True)
        self.Yield = channel.unary_unary(
                '/accelerator_orchestrator.v1alpha1.AcceleratorOrchestratorService/Yield',
                request_serializer=timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.YieldRequest.SerializeToString,
                response_deserializer=timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.YieldResponse.FromString,
                _registered_method=True)
        self.ListGroups = channel.unary_unary(
                '/accelerator_orchestrator.v1alpha1.AcceleratorOrchestratorService/ListGroups',
                request_serializer=timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.ListGroupsRequest.SerializeToString,
                response_deserializer=timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.ListGroupsResponse.FromString,
                _registered_method=True)
        self.GetGroupStatus = channel.unary_unary(
                '/accelerator_orchestrator.v1alpha1.AcceleratorOrchestratorService/GetGroupStatus',
                request_serializer=timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.GetGroupStatusRequest.SerializeToString,
                response_deserializer=timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.GetGroupStatusResponse.FromString,
                _registered_method=True)


class AcceleratorOrchestratorServiceServicer:
    """AcceleratorOrchestratorService provides APIs for managing accelerator orchestration.
    It coordinates access to shared accelerators among multiple jobs in a time-slice group.
    """

    def Acquire(self, request, context):
        """Acquire requests exclusive access to a time-slice group.
        This call blocks until access is granted.
        If the group is idle and the job's context is already RUNNING on the accelerator,
        it returns immediately. Otherwise, it queues the job and waits for the current
        locking_job to yield, then drives the snapshot/restore cycle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Yield(self, request, context):
        """Yield releases exclusive access to a time-slice group.
        It returns immediately to the caller once recorded, allowing the job to continue CPU-bound work
        without waiting for the snapshot to complete.
        If no other job is waiting in the queue, the snapshot is deferred (skipped)
        and the context remains live on the accelerator.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGroups(self, request, context):
        """ListGroups returns a list of all known time-slice group IDs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupStatus(self, request, context):
        """GetGroupStatus returns the detailed status of a specific time-slice group,
        including the current locking job, waiter queue depth, and individual job context states.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AcceleratorOrchestratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Acquire': grpc.unary_unary_rpc_method_handler(
                    servicer.Acquire,
                    request_deserializer=timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.AcquireRequest.FromString,
                    response_serializer=timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.AcquireResponse.SerializeToString,
            ),
            'Yield': grpc.unary_unary_rpc_method_handler(
                    servicer.Yield,
                    request_deserializer=timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.YieldRequest.FromString,
                    response_serializer=timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.YieldResponse.SerializeToString,
            ),
            'ListGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGroups,
                    request_deserializer=timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.ListGroupsRequest.FromString,
                    response_serializer=timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.ListGroupsResponse.SerializeToString,
            ),
            'GetGroupStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupStatus,
                    request_deserializer=timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.GetGroupStatusRequest.FromString,
                    response_serializer=timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.GetGroupStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accelerator_orchestrator.v1alpha1.AcceleratorOrchestratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('accelerator_orchestrator.v1alpha1.AcceleratorOrchestratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AcceleratorOrchestratorService:
    """AcceleratorOrchestratorService provides APIs for managing accelerator orchestration.
    It coordinates access to shared accelerators among multiple jobs in a time-slice group.
    """

    @staticmethod
    def Acquire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelerator_orchestrator.v1alpha1.AcceleratorOrchestratorService/Acquire',
            timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.AcquireRequest.SerializeToString,
            timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.AcquireResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Yield(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelerator_orchestrator.v1alpha1.AcceleratorOrchestratorService/Yield',
            timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.YieldRequest.SerializeToString,
            timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.YieldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelerator_orchestrator.v1alpha1.AcceleratorOrchestratorService/ListGroups',
            timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.ListGroupsRequest.SerializeToString,
            timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.ListGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroupStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelerator_orchestrator.v1alpha1.AcceleratorOrchestratorService/GetGroupStatus',
            timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.GetGroupStatusRequest.SerializeToString,
            timeslice_dot_orchestrator_dot___generated_dot_accelerator__orchestrator__pb2.GetGroupStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
