# Default values for llm-d-rl-time-slicing parent chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Override values for the acceleratororchestrator subchart
acceleratororchestrator:
  enabled: true
  # You can add specific overrides here, for example:
  # replicaCount: 2

# Override values for the snapshot-agent subchart
snapshot-agent:
  enabled: true
  image:
    tag: latest
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Equal"
      value: "present"
      effect: "NoSchedule"
    - key: "timeslice.io/shared"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

# Override values for the nvidia-dra-driver-gpu subchart
nvidia-dra-driver-gpu:
  enabled: true
  namespaceOverride: "timeslice-system"
  nvidiaDriverRoot: "/home/kubernetes/bin/nvidia/" # Use "/opt/nvidia" for Ubuntu nodes

  gpuResourcesEnabledOverride: true
  resources:
    computeDomains:
      enabled: false
  kubeletPlugin:
    priorityClassName: ""
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "cloud.google.com/gke-gpu"
              operator: "In"
              values:
              - "true"


