{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "acceleratororchestrator.fullname" . }}-configmap
  namespace: timeslice-system
  labels:
    {{- include "acceleratororchestrator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "acceleratororchestrator.fullname" . }}-configmap
subjects:
  - kind: ServiceAccount
    name: {{ include "acceleratororchestrator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
