apiVersion: v1
kind: Service
metadata:
  name: {{ include "acceleratororchestrator.fullname" . }}
  namespace: timeslice-system
  labels:
    {{- include "acceleratororchestrator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "acceleratororchestrator.selectorLabels" . | nindent 4 }}
